
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Priyadharshan
 */
public class Bakery_login extends javax.swing.JFrame {

    /**
     * Creates new form Bakery_login
     */
    public Bakery_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        create_user = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1560, 835));
        getContentPane().setLayout(null);

        username.setBackground(new java.awt.Color(250, 214, 214));
        username.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        username.setForeground(new java.awt.Color(223, 75, 75));
        username.setText("username");
        username.setBorder(null);
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(640, 440, 260, 50);

        password.setBackground(new java.awt.Color(250, 214, 214));
        password.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        password.setForeground(new java.awt.Color(223, 75, 75));
        password.setText("password");
        password.setBorder(null);
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(640, 530, 260, 40);

        login.setBackground(new java.awt.Color(223, 75, 75));
        login.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        login.setForeground(new java.awt.Color(212, 176, 176));
        login.setText("LOGIN");
        login.setBorder(null);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(590, 630, 70, 25);

        reset.setBackground(new java.awt.Color(223, 75, 75));
        reset.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(212, 176, 176));
        reset.setText("RESET");
        reset.setBorder(null);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(880, 630, 70, 25);

        create_user.setBackground(new java.awt.Color(223, 75, 75));
        create_user.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        create_user.setForeground(new java.awt.Color(212, 176, 176));
        create_user.setText("create new user");
        create_user.setBorder(null);
        create_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_userActionPerformed(evt);
            }
        });
        getContentPane().add(create_user);
        create_user.setBounds(700, 690, 150, 30);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bakeryloginbg.png"))); // NOI18N
        bg.setText("bg");
        getContentPane().add(bg);
        bg.setBounds(-10, -10, 1560, 835);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        username.setText("");
        password.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bakery","root","mysql");
            
            String sql = "Select * from bakery.bakery_login  where username=? and password=?"; 
            
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, username.getText());

            pst.setString(2, password.getText());

            ResultSet rs = pst.executeQuery();

            if(rs.next()){

            JOptionPane.showMessageDialog(null, "Username and Password Matched");
         
           Bakery_purchase s = new Bakery_purchase();
            s.setVisible(true); 
            
            } 
            else{

            JOptionPane.showMessageDialog(null, "Username and password not Correct");

            username.setText("");

            password.setText("");

            }

            con.close();

        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Bakery_login.class.getName()).log(Level.SEVERE, null, ex);
        } 

    }//GEN-LAST:event_loginActionPerformed

    private void create_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_userActionPerformed
        // TODO add your handling code here:
            Bakery_adduser p = new Bakery_adduser();
            p.setVisible(true);
    }//GEN-LAST:event_create_userActionPerformed

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        // TODO add your handling code here:
        username.setText("");
    }//GEN-LAST:event_usernameMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        // TODO add your handling code here:
        password.setText("");
    }//GEN-LAST:event_passwordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bakery_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bakery_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bakery_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bakery_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bakery_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton create_user;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton reset;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
