
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Priyadharshan
 */
public class Bakery_pay extends javax.swing.JFrame {

    /**
     * Creates new form bakery_pay
     */
    public Bakery_pay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card_holder_name = new javax.swing.JTextField();
        card_number = new javax.swing.JTextField();
        cvv = new javax.swing.JTextField();
        expiry_date = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        pay = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1560, 835));
        getContentPane().setLayout(null);

        card_holder_name.setBackground(new java.awt.Color(250, 214, 214));
        card_holder_name.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        card_holder_name.setForeground(new java.awt.Color(223, 75, 75));
        card_holder_name.setText("card holder name");
        card_holder_name.setBorder(null);
        card_holder_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card_holder_nameMouseClicked(evt);
            }
        });
        card_holder_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card_holder_nameActionPerformed(evt);
            }
        });
        getContentPane().add(card_holder_name);
        card_holder_name.setBounds(440, 410, 400, 50);

        card_number.setBackground(new java.awt.Color(250, 214, 214));
        card_number.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        card_number.setForeground(new java.awt.Color(223, 75, 75));
        card_number.setText("card number");
        card_number.setBorder(null);
        card_number.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card_numberMouseClicked(evt);
            }
        });
        getContentPane().add(card_number);
        card_number.setBounds(441, 512, 400, 40);

        cvv.setBackground(new java.awt.Color(250, 214, 214));
        cvv.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        cvv.setForeground(new java.awt.Color(223, 75, 75));
        cvv.setText("ccv");
        cvv.setBorder(null);
        cvv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cvvMouseClicked(evt);
            }
        });
        getContentPane().add(cvv);
        cvv.setBounds(254, 620, 170, 40);

        expiry_date.setBackground(new java.awt.Color(250, 214, 214));
        expiry_date.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        expiry_date.setForeground(new java.awt.Color(223, 75, 75));
        expiry_date.setText("expiry date");
        expiry_date.setBorder(null);
        expiry_date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expiry_dateMouseClicked(evt);
            }
        });
        getContentPane().add(expiry_date);
        expiry_date.setBounds(673, 622, 170, 40);

        location.setBackground(new java.awt.Color(250, 214, 214));
        location.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        location.setForeground(new java.awt.Color(223, 75, 75));
        location.setText("location");
        location.setBorder(null);
        location.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                locationMouseClicked(evt);
            }
        });
        getContentPane().add(location);
        location.setBounds(1004, 392, 360, 150);

        pay.setBackground(new java.awt.Color(223, 75, 75));
        pay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pay.setText("PAY NOW");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        getContentPane().add(pay);
        pay.setBounds(1130, 630, 120, 40);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bakery_card.png"))); // NOI18N
        bg.setText("bg");
        getContentPane().add(bg);
        bg.setBounds(-10, -10, 1570, 835);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void card_holder_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card_holder_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_card_holder_nameActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bakery","root","mysql");
            
            String query = "insert into bakery.bakery_purchase ( name, card_number, cvv, expirey_date, location)"+"values ( ?, ?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, card_holder_name.getText());
            pst.setString(2, card_number.getText());
            pst.setString(3, cvv.getText());
            pst.setString(4, expiry_date.getText());
            pst.setString(5, location.getText());

            pst.executeUpdate();
            Bakery_end r = new Bakery_end();
            r.setVisible(true);
            

            con.close();

        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Bakery_pay.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_payActionPerformed

    private void card_holder_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card_holder_nameMouseClicked
        // TODO add your handling code here:
        card_holder_name.setText("");
    }//GEN-LAST:event_card_holder_nameMouseClicked

    private void card_numberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card_numberMouseClicked
        // TODO add your handling code here:
        card_number.setText("");
    }//GEN-LAST:event_card_numberMouseClicked

    private void cvvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cvvMouseClicked
        // TODO add your handling code here:
        cvv.setText("");
    }//GEN-LAST:event_cvvMouseClicked

    private void expiry_dateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expiry_dateMouseClicked
        // TODO add your handling code here:
        expiry_date.setText("");
    }//GEN-LAST:event_expiry_dateMouseClicked

    private void locationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locationMouseClicked
        // TODO add your handling code here:
        location.setText("");
        
    }//GEN-LAST:event_locationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bakery_pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bakery_pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bakery_pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bakery_pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bakery_pay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JTextField card_holder_name;
    private javax.swing.JTextField card_number;
    private javax.swing.JTextField cvv;
    private javax.swing.JTextField expiry_date;
    private javax.swing.JTextField location;
    private javax.swing.JButton pay;
    // End of variables declaration//GEN-END:variables
}
